image:
  file: .gitpod.Dockerfile

tasks:
  - name: Set up AnkiHub
    env:
      COMPOSE_FILE: "local.yml"
    init: |
      git clone https://github.com/ankipalace/ankihub /workspace/ankihub
      cd /workspace/ankihub
      cp .env.dev .env
      docker-compose build
      docker-compose run --rm django bash -c ". release.sh"
    command: |
      docker-compose up -d
      gp ports await 8000
      docker-compose run --rm django bash

  - name: Set up Anki
    env:
      ANKIHUB_APP_URL: "http://localhost:8000"
      ANKIDEV: 1
      DEVELOPMENT: True
      ANKI_BASE_ROOT: "/tmp"

    init: |
      pyenv local 3.9.13
      python3 scripts/build.py
      python3 scripts/create_tmp_anki_data_dir.py
    command: |
      anki -p dev -b $ANKI_BASE_ROOT/Anki2

github:
  prebuilds:
    addBadge: true

vscode:
  extensions:
    - almenon.arepl
    - ms-python.python
    - littlefoxteam.vscode-python-test-adapter

ports:
  - port: 6080
    name: Anki Desktop
    visibility: public
    onOpen: open-browser
  - port: 5900
    onOpen: ignore
  - name: AnkiHub
    description: Web app
    port: 8000
    onOpen: ignore
  - name: postgres
    port: 5432
    onOpen: ignore
  - name: redis
    port: 6379
    onOpen: ignore
  - name: debugpy
    port: 3000
    onOpen: ignore
  - name: mailhog
    port: 8025
    onOpen: ignore
