# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
image:
  file: .gitpod.Dockerfile

tasks:
  - init: python -m pip install -r ./requirements/dev.txt
    command: python -m pytest tests

github:
  prebuilds:
    addComment: true

vscode:
  extensions:
    - littlefoxteam.vscode-python-test-adapter@0.3.16:tZ/6xOSSdKUaq6JCUVkD+A==
    - almenon.arepl@1.0.20:Uu7lIOwyLgmNWpTwCl/iqQ==
