image:
  file: .gitpod.Dockerfile

tasks:
  - init: pyenv local 3.9.13
    command: SKIP_INIT=1 python -m pytest tests

github:
  prebuilds:
    addComment: true

vscode:
  extensions:
    - almenon.arepl
    - ms-python.python
    - littlefoxteam.vscode-python-test-adapter
