# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
image:
  file: .gitpod.Dockerfile

tasks:
  - init: python -m pip install -r ./requirements/dev.txt

github:
  prebuilds:
    addComment: true
