image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      pyenv local 3.9.13
      python3 scripts/build.py
      mkdir -p /home/gitpod/.local/share/Anki2/addons21/
      ln -sf /workspace/ankihub_addon/ankihub/ /home/gitpod/.local/share/Anki2/addons21/
    env:
      ANKIHUB_APP_URL: "https://staging.ankihub.net"
      ANKIDEV: 1
      DEVELOPMENT: True
    command: |
      anki

github:
  prebuilds:
    addBadge: true

vscode:
  extensions:
    - almenon.arepl
    - ms-python.python
    - littlefoxteam.vscode-python-test-adapter

ports:
  - port: 6080
    visibility: public
  - port: 5900
    onOpen: ignore
