image:
  file: .gitpod.Dockerfile

tasks:
  - init: >
      pyenv local 3.9.13
    env:
      ANKIHUB_APP_URL: "https://staging.ankihub.net"
      ANKIDEV: 1
      DEVELOPMENT: True
      ANKI_BASE: "/workspace/ankihub_addon/ankihub/tests/test_data/Anki2"
    command: >
      anki -p dev

github:
  prebuilds:
    addComment: true
    addBadge: true

vscode:
  extensions:
    - almenon.arepl
    - ms-python.python
    - littlefoxteam.vscode-python-test-adapter

ports:
  - port: 6080
    onOpen: open-browser
    visibility: public
  - port: 5900
    onOpen: ignore
