image:
  file: .gitpod.Dockerfile

tasks:
  - name: Set up AnkiHub
    env:
      COMPOSE_FILE: "local.yml"
    init: |
      git clone https://github.com/ankipalace/ankihub /workspace/ankihub
      cd /workspace/ankihub
      cp .env.dev .env
      docker-compose build
      docker-compose run --rm django bash -c ". release.sh"
    command: |
      docker-compose up -d
      gp ports await 8000
      docker-compose run --rm django bash

  - name: Set up Anki
    env:
      ANKIHUB_APP_URL: "http://localhost:8000"
      ANKIDEV: 1
      DEVELOPMENT: True
    init: |
      pyenv local 3.9.13
      python3 scripts/build.py
      cp -r /workspace/ankihub_addon/tests/test_data/Anki2 /home/gitpod/.local/share/
      cp -r /workspace/ankihub_addon/tests/test_data/d1659f4e-4839-4498-8859-51d92576e1cc /workspace/ankihub_addon/ankihub/user_files
      ln -s /workspace/ankihub_addon/ankihub/ /home/gitpod/.local/share/Anki2/addons21/
    command: |
      anki

github:
  prebuilds:
    addBadge: true

vscode:
  extensions:
    - almenon.arepl
    - ms-python.python
    - littlefoxteam.vscode-python-test-adapter

ports:
  - port: 6080
    name: Anki Desktop
    visibility: public
    onOpen: open-browser
  - port: 5900
    onOpen: ignore
  - name: AnkiHub
    description: Web app
    port: 8000
    onOpen: open-browser
  - name: postgres
    port: 5432
    onOpen: ignore
  - name: redis
    port: 6379
    onOpen: ignore
  - name: debugpy
    port: 3000
    onOpen: ignore
  - name: mailhog
    port: 8025
    onOpen: ignore
