[tool.isort]
profile = 'black'

[tool.black]
extend-exclude = '''
(
  lib/
)
'''

[tool.mypy]
files = ['ankihub', 'tests/addon', 'tests/client']

exclude = [
  'ankihub/media_import',
  'ankihub/media_export',
  'ankihub/gui/ankiaddonconfig',
  'ankihub/lib/sentry_sd',
  'ankihub/lib/urllib',
  'ankihub/lib/other/typing_extension',
  'ankihub/lib/tenacity',
  'ankihub/lib/peewee',
  'ankihub/lib/structlog',
]

no_strict_optional = true

[[tool.mypy.overrides]]
module = 'ankihub.*'
check_untyped_defs = true

[[tool.mypy.overrides]]
module = [
  'ankihub.media_import.*',
  'ankihub.media_export.*',
  'structlog.*',
  'mashumaro.*',
  'ankihub.gui.ankiaddonconfig.*',
  'sentry_sdk.*',
  'urllib3.*',
  'tenacity.*',
  'peewee.*',
]
ignore_errors = true

[[tool.mypy.overrides]]
module = 'anki._vendor.*'
ignore_missing_imports = true
