[tool.isort]
profile = 'black'

[tool.black]
extend-exclude = '''
(
  lib/
)
'''

[tool.mypy]
files = ['ankihub', 'tests/addon', 'tests/client']

exclude = [
  'ankihub/media_import',
  'ankihub/media_export',
  'ankihub/gui/ankiaddonconfig',
  'ankihub/lib/certifi',
  'ankihub/lib/sentry_sd',
  'ankihub/lib/urllib',
  'ankihub/lib/other/typing_extension',
  'ankihub/lib/tenacity',
]

no_strict_optional = true

[[tool.mypy.overrides]]
module = 'ankihub.*'
check_untyped_defs = true

[[tool.mypy.overrides]]
module = 'mashumaro.*'
ignore_errors = true

[[tool.mypy.overrides]]
module = ['sentry_sdk.*', 'certifi.*', 'urllib3.*', 'tenacity.*']
follow_imports = 'skip'

[[tool.mypy.overrides]]
module = 'ankihub.gui.ankiaddonconfig.*'
ignore_errors = true
