name: Setup addon
inputs:
  google_api_key:
    required: true
  install_qt:
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Qt
      if: ${{ inputs.install_qt == 'true' }}
      uses: jurplel/install-qt-action@v4
      with:
        version: "5.15.2"
        setup-python: false
        cache: true
      continue-on-error: true

    - name: Install deps
      run: |
        # We need to use Qt5 instead of Qt6 for CI because Qt6 has
        # compatibility issues in the CI environment.
        sed -i 's/\[qt6\]/[qt5]/' requirements/*.txt

        uv pip install -r ./requirements/dev.txt
      shell: bash

    - name: Build
      run: |
        uv run ./scripts/build.py
      shell: bash
      env:
        GOOGLE_API_KEY: ${{ inputs.google_api_key }}
