name: Setup addon
inputs:
  google_api_key:
    required: true
  install_qt:
    required: true
  aqt_dependency_group:
    required: false
  qt_package:
    required: false
runs:
  using: "composite"
  steps:
    - name: Install dependencies and detect Qt version
      if: ${{ inputs.install_qt == 'true' }}
      run: |
        uv sync --group ${{ inputs.aqt_dependency_group }}
        QT_VERSION=$(uv pip show ${{ inputs.qt_package }} | sed -n 's/^Version: //p')
        echo "QT_VERSION=$QT_VERSION" >> $GITHUB_ENV
        echo "PYTEST_QT_API=${{ inputs.qt_package }}" >> $GITHUB_ENV

    - name: Install Qt
      if: ${{ inputs.install_qt == 'true' }}
      uses: jurplel/install-qt-action@v4
      with:
        version: ${{ env.QT_VERSION }}
        setup-python: false
        cache: true
      continue-on-error: true

    - name: Install additional Qt6 dependencies
      if: ${{ inputs.install_qt == 'true' && startsWith(inputs.qt_version, '6.') }}
      run: |
        sudo apt-get update
        sudo apt-get -y install libgl1 libegl1 libdbus-1-3 libnss3 libxdamage1 libxkbcommon0 libasound2t64
      shell: bash

    - name: Build
      run: |
        uv run ./scripts/build.py
      shell: bash
      env:
        GOOGLE_API_KEY: ${{ inputs.google_api_key }}
