name: Setup addon
inputs:
  google_api_key:
    required: true
  install_qt:
    required: true
runs:
  using: "composite"
  steps:
    - name: Get pip cache dir
      id: pip-cache
      run: |
        python -m pip install --upgrade pip
        echo "::set-output name=dir::$(pip cache dir)"
      shell: bash

    - name: pip cache
      uses: actions/cache@v3
      with:
        path: |
          ${{ steps.pip-cache.outputs.dir }}
          ~/.cache/pre-commit
        key: ${{ runner.os }}-pip-${{ hashFiles('**/dev.txt', '**/base.txt', '.pre-commit-config.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Qt
      if: ${{ inputs.install_qt == 'true' }}
      uses: jurplel/install-qt-action@v3
      with:
        version: "5.15.2"
        setup-python: false
        cache: true
      continue-on-error: true

    - name: Install deps
      run: |
        python -m pip install -r ./requirements/dev.txt
      shell: bash

    - name: Build
      run: |
        python ./scripts/build.py
      shell: bash
      env:
        GOOGLE_API_KEY: ${{ inputs.google_api_key }}
