name: Setup addon
inputs:
  google_api_key:
    required: true
  install_qt:
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Qt
      if: ${{ inputs.install_qt == 'true' }}
      uses: jurplel/install-qt-action@v4
      with:
        version: "5.15.2"
        setup-python: false
        cache: true
      continue-on-error: true

    - name: Install additional Qt dependencies
      if: ${{ inputs.install_qt == 'true' }}
      run: |
        sudo apt-get -y install xvfb x11-utils libgl1 libegl1 libdbus-1-3
      shell: bash

    - name: Install deps
      run: |
        uv sync --locked --dev
      shell: bash

    - name: Build
      run: |
        uv run ./scripts/build.py
      shell: bash
      env:
        GOOGLE_API_KEY: ${{ inputs.google_api_key }}
