"""Logic for the initial steps of registering local decks with collaborative
decks for both deck creators and deck users.
"""
import json
import os
import pathlib
import tempfile
import uuid
import typing

from PyQt6.QtCore import qDebug
from anki.exporting import AnkiPackageExporter
from anki.models import NoteType
from aqt import mw
from aqt.dbcheck import check_db
from aqt.utils import askUser, tooltip

from . import constants
from .ankihub_client import AnkiHubClient
from .constants import ANKIHUB_NOTE_TYPE_FIELD_NAME, URL_VIEW_NOTE
from .utils import get_note_types_in_deck, update_or_create_note

DIR_PATH = os.path.dirname(os.path.abspath(__file__))


def process_csv(notes: typing.List[dict]) -> None:
    """Populate the AnkiHub ID field that was added to the Note Type by
    modify_note_type."""
    for note_data in notes:
        (
            ankihub_id,
            anki_id,
            tags,
            deck,
            last_sync,
            fields,
            note_type,
            note_type_id,
        ) = note_data.values()
        # the fields column generated by parse_notes_to_csv isn’t valid json
        fields = json.loads(fields.replace("'", '"'))
        tags = json.loads(tags.replace("'", '"'))
        update_or_create_note(anki_id, ankihub_id, fields, tags, note_type)
    check_db(mw)


def modify_note_type(note_type) -> None:
    """Adds the AnkiHub Field to the Note Type and modifies the template to
    display the field.
    """
    "Adds ankihub field. Adds link to ankihub in card template."
    qDebug(f"Modifying note type {note_type}")
    note_type = mw.col.models.by_name(note_type)
    mm = mw.col.models
    fields = note_type["flds"]
    field_names = [field["name"] for field in fields]
    if constants.ANKIHUB_NOTE_TYPE_FIELD_NAME in field_names:
        qDebug(f"{constants.ANKIHUB_NOTE_TYPE_FIELD_NAME} already exists.")
        return
    ankihub_field = mm.new_field(constants.ANKIHUB_NOTE_TYPE_FIELD_NAME)
    note_type["flds"].insert(0, ankihub_field)
    # TODO Genericize this by creating a function that takes a template and
    #  returns a new template.
    template_snippet = (
        "\n\n<br><br>"
        f"\n{{{{#{ANKIHUB_NOTE_TYPE_FIELD_NAME}}}}}\n"
        "<a class='ankihub' "
        f"href='{URL_VIEW_NOTE}{{{{{ANKIHUB_NOTE_TYPE_FIELD_NAME}}}}}'>"
        "\nView Note on AnkiHub\n"
        "</a>"
        f"\n{{{{/{ANKIHUB_NOTE_TYPE_FIELD_NAME}}}}}\n"
    )

    templates = note_type["tmpls"]
    for template in templates:
        template["afmt"] += template_snippet
    mm.save(note_type)


def modify_note_types(note_types: typing.Iterable[str]):
    for note_type in note_types:
        modify_note_type(note_type)
    # TODO Run add_id_fields


def upload_deck(did: int) -> None:
    """Upload the deck to AnkiHub."""
    deck_name = mw.col.decks.name(did)
    exporter = AnkiPackageExporter(mw.col)
    exporter.did = did
    exporter.includeMedia = False
    exporter.includeTags = True
    deck_uuid = uuid.uuid4()
    out_dir = pathlib.Path(tempfile.mkdtemp())
    out_file = str(out_dir / f"export-{deck_uuid}.apkg")
    exporter.exportInto(out_file)
    ankihub_client = AnkiHubClient()
    response = ankihub_client.upload_deck(f"{deck_name}.apkg")
    tooltip("Deck Uploaded to AnkiHub")
    return response


def _create_collaborative_deck(note_types, did):
    modify_note_types(note_types)
    upload_deck(did)


def create_collaborative_deck(did: int) -> None:
    model_ids = get_note_types_in_deck(did)
    note_types = [mw.col.models.get(model_id) for model_id in model_ids]
    names = ", ".join([note["name"] for note in note_types])
    response = askUser(
        "Uploading the deck to AnkiHub will modify the following note types, "
        f"and will require a full sync afterwards: {names}.  Continue?",
        title="AnkiHub",
    )
    if not response:
        tooltip("Cancelled Upload to AnkiHub")
        return
    mw.taskman.with_progress(
        task=lambda: _create_collaborative_deck(note_types, did),
        on_done=lambda future: tooltip("Deck Uploaded to AnkiHub"),
    )
