name: "Set up project"
description: "Set up project"

defaults:
  run:
    shell: bash
    working-directory: pytest-anki


runs:
  using: "composite"
  steps:
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.1.8
        virtualenvs-create: false

    - name: Checkout pytest-anki
      uses: actions/checkout@v2
      with:
        repository: glutanimate/pytest-anki
        path: pytest-anki

    - name: Set up pytest-anki
      shell: bash
      run: |
        poetry install
