name: "Set up project"
description: "Set up project"

runs:
  using: "composite"
  steps:
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.1.8
        virtualenvs-create: false

    - name: Set up pytest-anki
      shell: bash
      run: |
        make install
