name: Static Checks

on:
  pull_request:

jobs:
  static-checks:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code Repository
        uses: actions/checkout@v3.5.0

      - name: Set up Python 3.8
        uses: actions/setup-python@v4.7.0
        if: ${{ steps.filter.outputs.py == 'true' }}
        with:
          python-version: 3.10

      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"

      - name: pip cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.pip-cache.outputs.dir }}
            ~/.cache/pre-commit
          key: ${{ runner.os }}-pip-${{ hashFiles('**/dev.txt', '.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ./requirements/dev.txt

      - name: Build
        run: |
          python ./scripts/build.py
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

      - name: Run pre-commit
        run: pre-commit run --all

      - name: Run mypy
        run: mypy
