name: tests

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  test-current-anki:
    runs-on: macos-latest

    steps:
      - name: Checkout ankihub_addon
        uses: actions/checkout@v2

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ./requirements/dev.txt

      - name: Run tests forked
        run: pytest --forked --cov --cov-report=xml
        env:
          SKIP_INIT: 1

      - name: Run tests
        if: always()
        run: pytest --cov --cov-report=xml
        env:
          SKIP_INIT: 1

      - name: Upload coverage to Codecov
        env:
         CODECOV_TOKEN: "${{ secrets.CODECOV_TOKEN }}"
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true

      - name: Run pre-commit
        run: pre-commit run --all-files
