name: tests
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  COMPOSE_FILE: ${{ github.workspace }}/ankihub_web/local.yml

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v3
        with:
          python-version: "3.9.7"

      - name: Checkout ankihub_addon
        uses: actions/checkout@v3

      - name: Enable cloning web app repo
        uses: webfactory/ssh-agent@v0.5.4
        with:
            ssh-private-key: ${{ secrets.ANKIHUB_SSH_PRIVATE_KEY }}

      - name: Checkout ankipalace/ankihub web app repo
        uses: actions/checkout@v3
        with:
          repository: ankipalace/ankihub
          ref: dev
          path: ankihub_web

      - name: Set up AnkiHub env
        run: |
          mv ${{ github.workspace }}/ankihub_web/.env.dev ${{ github.workspace }}/ankihub_web/.env
          echo DEPLOYMENT_ENVIRONMENT=local >> ${{ github.workspace }}/ankihub_web/.env

      - name: Get pip cache dir
        id: pip-cache
        run: |
          python -m pip install --upgrade pip
          echo "::set-output name=dir::$(pip cache dir)"

      - name: pip cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.pip-cache.outputs.dir }}
            ~/.cache/pre-commit
          key: ${{ runner.os }}-pip-${{ hashFiles('**/dev.txt', '**/base.txt', '.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - run: docker-compose pull
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - run: |
          docker-compose build
          docker-compose run --rm django python manage.py makemigrations
          docker-compose run --rm django bash release.sh
          docker-compose up -d

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: "5.15.2"
          setup-python: "false"

      - name: Install deps
        run: python -m pip install -r ./requirements/dev.txt

      - name: Build
        run: |
          python ./scripts/build.py
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

      - name: Run pytest with coverage
        run: pytest ./tests --cov --cov-report=xml --disable-vcr

      - name: Upload coverage to Codecov
        env:
          CODECOV_TOKEN: "${{ secrets.CODECOV_TOKEN }}"
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: false

      - name: Create ankiaddon file
        run: |
          bash ./scripts/release.sh
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

      - name: Archive .ankiaddon
        uses: actions/upload-artifact@v3
        with:
          name: ankihub_addon_${{ github.sha }}
          path: ankihub.ankiaddon

      - name: Run pre-commit
        run: pre-commit run --all-files

      - name: Run mypy
        run: mypy ankihub
