name: tests

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ankihub_addon
        uses: actions/checkout@v2

      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.9.7"
          # architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: "5.15.2"
          setup-python: "false"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ./requirements/dev.txt

      - name: Build
        run: |
          python ./scripts/build.py
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

      - name: Run pytest
        run: pytest ./tests

      - name: Create ankiaddon file
        run: |
          echo ${{ steps.vars.outputs.version }} > VERSION
          bash ./scripts/release.sh

      - name: Archive .ankiaddon
        uses: actions/upload-artifact@v3
        with:
          name: ankihub_addon_${{ github.sha }}
          path: ankihub.ankiaddon

      - name: Run pre-commit
        run: pre-commit run --all-files

      - name: Run mypy
        run: mypy ankihub
