name: tests

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ankihub_addon
        uses: actions/checkout@v2

      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9.7'
          # architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: "6.3.1"
          setup-python: 'false'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ./requirements/dev.txt

      - name: Run pytest
        run: pytest -vvv --cov --cov-report=xml --forked ./tests
        env:
          SKIP_INIT: 1

      - name: Package .ankiaddon
        run: zip -r "../ankihub_${GITHUB_SHA}.ankiaddon" . -x ./tests\*
        working-directory: ankihub

      - name: Archive .ankiaddon
        uses: actions/upload-artifact@v3
        with:
          name: ankihub_addon_${{ github.sha }}
          path: ankihub_${{ github.sha }}.ankiaddon

      - name: Upload coverage to Codecov
        env:
          CODECOV_TOKEN: "${{ secrets.CODECOV_TOKEN }}"
        uses: codecov/codecov-action@v1

      - name: Run pre-commit
        run: pre-commit run --all-files

      - name: Run mypy
        run: |
          python -m pip install types-requests
          mypy ankihub
