name: tests
env:
  COMPOSE_DOCKER_CLI_BUILD: 1
  WEBAPP_COMPOSE_FILE: ${{ github.workspace }}/ankihub_web/compose.yml
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  DISABLE_QT5_COMPAT: 1
  QTWEBENGINE_CHROMIUM_FLAGS: --no-sandbox

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  test-addon:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Checkout ankihub_addon
        uses: actions/checkout@v3

      - name: Install non-python deps
        run: |
          sudo apt-get update
          sudo apt-get install -y pyqt5-dev-tools xvfb jq

      - name: Install python deps
        run: |
          python -m pip install -r ./requirements/dev.txt
        shell: bash

      - name: Build
        run: |
          python ./scripts/build.py
        shell: bash
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

      - name: Run pytest with coverage
        run: |
          pytest ./tests/addon --cov --cov-report=xml -n 4
          pytest ./tests/addon --performance -k performance -n1 --cov-report=xml --cov-append
