name: tests

on:
  pull_request:
    branches: ["main"]

jobs:
  tests:
    # Use macos-latest to avoid complex system dependencies needed on ubuntu.
    runs-on: macos-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8

      - name: Checkout ankihub-addon
        uses: actions/checkout@v2

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements/dev.txt

      - name: Run tests
        run: ./run_tests.sh

      - name: Run flake8
        run: flake8

      - name: Run black
        run: black --check --diff .

      - name: Run mypy
        run: mypy .
