name: tests
env:
  COMPOSE_DOCKER_CLI_BUILD: 1
  WEBAPP_COMPOSE_FILE: ${{ github.workspace }}/ankihub_web/compose.yml
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  DISABLE_QT5_COMPAT: 1
  QTWEBENGINE_CHROMIUM_FLAGS: --no-sandbox

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  test-addon:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - replace_anki_version: false
          - replace_anki_version: true
            anki_package_version: 'aqt[qt5]==2.1.56'
    timeout-minutes: 30
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Checkout ankihub_addon
        uses: actions/checkout@v3

      - name: Setup addon
        uses: ./.github/actions/setup-addon
        with:
          google_api_key: ${{ secrets.GOOGLE_API_KEY }}
          install_qt: true

      - name: Replace Anki version
        if: ${{ matrix.replace_anki_version }}
        run: pip install "${{ matrix.anki_package_version }}"

      - name: Run pytest with coverage
        run: |
          pytest ./tests/addon -k get_document_body -n 1
          pytest ./tests/addon -k suggestion_button -n 1
          pytest ./tests/addon --cov --cov-report=xml -n 4
          pytest ./tests/addon --performance -k performance -n1 --cov-report=xml --cov-append
