name: Checks

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest black mypy anki aqt wheel
          # TODO: Install from glutanimate/pytest-anki.git once issues
          # addressed by my patch are sorted out.
          pip install git+https://github.com/andrewsanchez/pytest-anki.git

      - name: Run flake8
        run: flake8 ./src

      - name: Run black
        run: black --check --diff .

      - name: Run mypy
        run: mypy --no-strict-optional .

      - name: Run tests
        working-directory: ./src
        run: pytest
