name: tests

defaults:
  run:
    shell: bash
    working-directory: pytest-anki

on:
  push:

jobs:
  read-current-anki-matrix:
    # Reads current Anki set-up from anki-current.json
    runs-on: ubuntu-latest
    
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    
    steps:
    - name: Checkout pytest-anki
      uses: actions/checkout@v2
      with:
        repository: glutanimate/pytest-anki
        path: pytest-anki
    - id: set-matrix
      run: |
        content=$(cat ./anki-current.json)
        content="${content//'%'/'%25'}"
        content="${content//$'\n'/'%0A'}"
        content="${content//$'\r'/'%0D'}"
        content="{ \"include\": [ ${content} ] }"
        echo "::set-output name=matrix::$content"

  check-current-anki:
    needs: read-current-anki-matrix
    runs-on: ubuntu-18.04

    strategy:
      matrix: ${{ fromJSON(needs.read-current-anki-matrix.outputs.matrix) }}

    steps:
      - name: Checkout pytest-anki
        uses: actions/checkout@v2

      - name: Set up test environment
        uses: ./.github/actions/setup
        with:
          python: ${{ matrix.python }}
          chrome: ${{ matrix.chrome }}
          anki: ${{ matrix.anki }}
          pyqt: ${{ matrix.pyqt }}
          pyqtwebengine: ${{ matrix.pyqtwebengine }}

      - name: Run type checker for Anki ${{ matrix.anki }}
        shell: bash
        run: |
          make check

      - name: Run linter for Anki ${{ matrix.anki }}
        shell: bash
        run: |
          make lint

  test-current-anki:
    needs: read-current-anki-matrix
    runs-on: ubuntu-18.04

    strategy:
      matrix: ${{ fromJSON(needs.read-current-anki-matrix.outputs.matrix) }}

    steps:
      - name: Checkout pytest-anki
        uses: actions/checkout@v2
        with:
          repository: glutanimate/pytest-anki
          path: pytest-anki

      - name: Set up test environment
        uses: ./.github/actions/setup
        with:
          python: ${{ matrix.python }}
          chrome: ${{ matrix.chrome }}
          anki: ${{ matrix.anki }}
          pyqt: ${{ matrix.pyqt }}
          pyqtwebengine: ${{ matrix.pyqtwebengine }}

      - name: Checkout pytest-anki
        uses: actions/checkout@v2

      - name: Install deps
        run: pip install -r ./requirements/dev.txt

      - name: Run tests
        run: pytest src/tests
