name: Upload to AnkiWeb

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      GOOGLE_API_KEY:
        required: true
      ANKIWEB_USERNAME:
        required: true
      ANKIWEB_PASSWORD:
        required: true

jobs:
  upload-to-ankiweb:
    name: Upload to AnkiWeb
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"


      - name: Install deps
        run: |
          uv sync --locked --dev --group production

      - name: Create ankiaddon file
        run: |
          bash ./scripts/release.sh
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

      - name: Run upload script
        run: |
          uv run --group ankiweb scripts/upload_to_ankiweb.py ankihub.ankiaddon ankiweb_description.html https://ankihub.net/support
        env:
          ANKI_USERNAME: ${{ secrets.ANKIWEB_USERNAME }}
          ANKI_PASSWORD: ${{ secrets.ANKIWEB_PASSWORD }}
