name: Upload to AnkiWeb

on:
  workflow_dispatch:
  workflow_call:

jobs:
  upload-to-ankiweb:
    name: Upload to AnkiWeb
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create ankiaddon file
        run: bash ../scripts/release.sh
        working-directory: ankihub

      - name: Setup Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install git+https://github.com/nateshmbhat/webbot.git@333f51840cd5a1fcde0b014bd6ab401d51e62860
          python -m pip install webdriver_manager
          python -m pip uninstall -y selenium
          python -m pip install selenium==3.141.0

      - name: Run upload script
        run: |
          python scripts/upload_to_ankiweb.py ankihub.ankiaddon ankipalace ankihub_addon
        env:
          ANKI_USERNAME: hub@ankipalace.com
          ANKI_PASSWORD: ${{ secrets.ANKIWEB_PASSWORD }}
